combine bdt80.root -M MultiDimFit --saveWorkspace -n bdt80.postfit --robustFit=1 --cminDefaultMinimizerStrategy 0 --cminDefaultMinimizerTolerance 0.5 --setCrossingTolerance=0.0002
combine higgsCombinebdt80.postfit.MultiDimFit.mH120.root -M MultiDimFit -n bdt80.total --algo grid --points 50 --snapshotName MultiDimFit --redefineSignalPOIs BR --setParameterRanges BR=-0.1,0.1 --robustFit=1 --cminDefaultMinimizerStrategy 0 --cminDefaultMinimizerTolerance 0.5 --setCrossingTolerance=0.0002
combine higgsCombinebdt80.postfit.MultiDimFit.mH120.root -M MultiDimFit --algo grid --points 50 --snapshotName MultiDimFit --redefineSignalPOIs BR --setParameterRanges BR=-0.1,0.1 --freezeNuisanceGroups JEC_JER -n bdt80.freeze_JEC_JER --robustFit=1 --cminDefaultMinimizerStrategy 0 --cminDefaultMinimizerTolerance 0.5 --setCrossingTolerance=0.0002
combine higgsCombinebdt80.postfit.MultiDimFit.mH120.root -M MultiDimFit --algo grid --points 50 --snapshotName MultiDimFit --redefineSignalPOIs BR --setParameterRanges BR=-0.1,0.1 --freezeNuisanceGroups JEC_JER,b_c_tagging -n bdt80.freeze_JEC_JER_b_c_tagging --robustFit=1 --cminDefaultMinimizerStrategy 0 --cminDefaultMinimizerTolerance 0.5 --setCrossingTolerance=0.0002
combine higgsCombinebdt80.postfit.MultiDimFit.mH120.root -M MultiDimFit --algo grid --points 50 --snapshotName MultiDimFit --redefineSignalPOIs BR --setParameterRanges BR=-0.1,0.1 --freezeNuisanceGroups JEC_JER,b_c_tagging,Modeling -n bdt80.freeze_JEC_JER_b_c_tagging_Modeling --robustFit=1 --cminDefaultMinimizerStrategy 0 --cminDefaultMinimizerTolerance 0.5 --setCrossingTolerance=0.0002
combine higgsCombinebdt80.postfit.MultiDimFit.mH120.root -M MultiDimFit --algo grid --points 50 --snapshotName MultiDimFit --redefineSignalPOIs BR --setParameterRanges BR=-0.1,0.1 --freezeNuisanceGroups JEC_JER,b_c_tagging,Modeling,luminosity_pileup -n bdt80.freeze_JEC_JER_b_c_tagging_Modeling_lumi --robustFit=1 --cminDefaultMinimizerStrategy 0 --cminDefaultMinimizerTolerance 0.5 --setCrossingTolerance=0.0002
combine higgsCombinebdt80.postfit.MultiDimFit.mH120.root -M MultiDimFit --algo grid --points 50 --snapshotName MultiDimFit --redefineSignalPOIs BR --setParameterRanges BR=-0.1,0.1 --freezeNuisanceGroups JEC_JER,b_c_tagging,Modeling,luminosity_pileup,Normalization -n bdt80.freeze_JEC_JER_b_c_tagging_Modeling_lumi_norm --robustFit=1 --cminDefaultMinimizerStrategy 0 --cminDefaultMinimizerTolerance 0.5 --setCrossingTolerance=0.0002
combine higgsCombinebdt80.postfit.MultiDimFit.mH120.root -M MultiDimFit --algo grid --points 50 --snapshotName MultiDimFit --redefineSignalPOIs BR --setParameterRanges BR=-0.1,0.1 --freezeParameters allConstrainedNuisances -n bdt80.freeze_all --robustFit=1 --cminDefaultMinimizerStrategy 0 --cminDefaultMinimizerTolerance 0.5 --setCrossingTolerance=0.0002
plot1DScan.py higgsCombinebdt80.total.MultiDimFit.mH120.root --main-label "Total Uncert." --others higgsCombinebdt80.freeze_JEC_JER.MultiDimFit.mH120.root:"freeze JEC_JER":4 higgsCombinebdt80.freeze_JEC_JER_b_c_tagging.MultiDimFit.mH120.root:"freeze JEC_JER+bc_tagging":7 higgsCombinebdt80.freeze_JEC_JER_b_c_tagging_Modeling.MultiDimFit.mH120.root:"freeze +modeling":2 higgsCombinebdt80.freeze_JEC_JER_b_c_tagging_Modeling_lumi.MultiDimFit.mH120.root:"freeze +lumi":8 higgsCombinebdt80.freeze_JEC_JER_b_c_tagging_Modeling_lumi_norm.MultiDimFit.mH120.root:"freeze +norm":9 higgsCombinebdt80.freeze_all.MultiDimFit.mH120.root:"stat only":6 --output breakdown --breakdown "JEC,bctagging,modeling,lumi,norm,rest,stat" --POI BR
